<?php
abstract class Tile
{
    abstract public function getWealthFactor():int;
}
class Plains extends Tile
{
    private int $wealthfactor=2;
    public function getWealthFactor(): int
    {
        // TODO: Implement getWealthFactor() method.
        return $this->wealthfactor;
    }
}
class DiamondPlains extends Plains
{
    public function getWealthFactor(): int
    {
        return parent::getWealthFactor() +2; // TODO: Change the autogenerated stub
    }
}
class PollutedPlains extends Plains
{
    public function getWealthFactor(): int
    {
        return parent::getWealthFactor() -4; // TODO: Change the autogenerated stub
    }
}
$tile=new PollutedPlains();
print $tile->getWealthFactor();